version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests
  pre_build:
    commands:
      - echo Pre-build phase started...
      - mvn validate
  build:
    commands:
      - echo Build phase started...
      - mvn compile
      - mvn package
  post_build:
    commands:
      - echo Post-build phase started...
      - mvn test
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
